### ISSUE TITLE
Running 'hence compose' without any flags/args produces an error, missing --access-key

### ISSUE THREAD

**Issue by homertherefore** [hence-io/cli#1]
Ideally the command should produce the help info whenever no flags/args are entered. 

If an essential flag/arg is missing that it needs to run, serving an error to help educate the user on what they missed.

Error Reported:

``` bash
/usr/local/lib/node_modules/hence-cli/lib/index.js:49
        '--access-key=' + machine.apiKey.publicValue,
                                        ^
TypeError: Cannot read property 'publicValue' of undefined
    at _compose (/usr/local/lib/node_modules/hence-cli/lib/index.js:49:41)
    at Command.<anonymous> (/usr/local/lib/node_modules/hence-cli/lib/index.js:88:7)
    at Command.listener (/usr/local/lib/node_modules/hence-cli/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/local/lib/node_modules/hence-cli/node_modules/commander/index.js:610:12)
    at Command.parse (/usr/local/lib/node_modules/hence-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/hence-cli/lib/index.js:101:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by ghost** [comment]
Should be fixed in v0.0.12.  Please try again and close on confirmation.
